// bank-vocab.js — PURE DATA: vocabulary bank (120 items) transcribed from docs/story.md.
// Item = { id, family:'vocab', tier:1..4, form:'vocab'|'syn', prompt, choices[4], correctIndex }
// Convention: correct answer FIRST (correctIndex 0) — sampler shuffles position at serve time.
// vocab (en→th): choices are Thai; distractors from the SAME semantic field (near-miss rule).
// syn (en≈en): tier 4 only; distractors = same-topic words with clearly different meanings.
// Word list: high-frequency words following the Thai curriculum bands (ป.1–3 → ม.ปลาย+).
(function (global) {
'use strict';

const ITEMS = [
/* ---------- tier 1 · ป.1–3 · animals, colors, family, food, school, body ---------- */
{ id: 'v101', family: 'vocab', tier: 1, form: 'vocab', prompt: 'cat = ?', choices: ['แมว', 'หมา', 'นก', 'ปลา'], correctIndex: 0 },
{ id: 'v102', family: 'vocab', tier: 1, form: 'vocab', prompt: 'dog = ?', choices: ['หมา', 'แมว', 'กระต่าย', 'หนู'], correctIndex: 0 },
{ id: 'v103', family: 'vocab', tier: 1, form: 'vocab', prompt: 'bird = ?', choices: ['นก', 'ไก่', 'เป็ด', 'กา'], correctIndex: 0 },
{ id: 'v104', family: 'vocab', tier: 1, form: 'vocab', prompt: 'fish = ?', choices: ['ปลา', 'กุ้ง', 'ปู', 'หมึก'], correctIndex: 0 },
{ id: 'v105', family: 'vocab', tier: 1, form: 'vocab', prompt: 'elephant = ?', choices: ['ช้าง', 'แรด', 'ฮิปโป', 'ยีราฟ'], correctIndex: 0 },
{ id: 'v106', family: 'vocab', tier: 1, form: 'vocab', prompt: 'monkey = ?', choices: ['ลิง', 'กอริลลา', 'ชิมแปนซี', 'เสือ'], correctIndex: 0 },
{ id: 'v107', family: 'vocab', tier: 1, form: 'vocab', prompt: 'rabbit = ?', choices: ['กระต่าย', 'หนู', 'กระรอก', 'แฮมสเตอร์'], correctIndex: 0 },
{ id: 'v108', family: 'vocab', tier: 1, form: 'vocab', prompt: 'red = ?', choices: ['สีแดง', 'สีชมพู', 'สีส้ม', 'สีน้ำตาล'], correctIndex: 0 },
{ id: 'v109', family: 'vocab', tier: 1, form: 'vocab', prompt: 'blue = ?', choices: ['สีน้ำเงิน', 'สีฟ้า', 'สีม่วง', 'สีเขียว'], correctIndex: 0 },
{ id: 'v110', family: 'vocab', tier: 1, form: 'vocab', prompt: 'green = ?', choices: ['สีเขียว', 'สีเหลือง', 'สีน้ำเงิน', 'สีขาว'], correctIndex: 0 },
{ id: 'v111', family: 'vocab', tier: 1, form: 'vocab', prompt: 'yellow = ?', choices: ['สีเหลือง', 'สีส้ม', 'สีทอง', 'สีครีม'], correctIndex: 0 },
{ id: 'v112', family: 'vocab', tier: 1, form: 'vocab', prompt: 'mother = ?', choices: ['แม่', 'พ่อ', 'ยาย', 'ป้า'], correctIndex: 0 },
{ id: 'v113', family: 'vocab', tier: 1, form: 'vocab', prompt: 'father = ?', choices: ['พ่อ', 'แม่', 'ปู่', 'ลุง'], correctIndex: 0 },
{ id: 'v114', family: 'vocab', tier: 1, form: 'vocab', prompt: 'friend = ?', choices: ['เพื่อน', 'ศัตรู', 'ครู', 'เพื่อนบ้าน'], correctIndex: 0 },
{ id: 'v115', family: 'vocab', tier: 1, form: 'vocab', prompt: 'family = ?', choices: ['ครอบครัว', 'บ้าน', 'เพื่อน', 'ญาติ'], correctIndex: 0 },
{ id: 'v116', family: 'vocab', tier: 1, form: 'vocab', prompt: 'rice = ?', choices: ['ข้าว', 'ขนมปัง', 'ก๋วยเตี๋ยว', 'เกลือ'], correctIndex: 0 },
{ id: 'v117', family: 'vocab', tier: 1, form: 'vocab', prompt: 'egg = ?', choices: ['ไข่', 'นม', 'ไก่', 'ขนม'], correctIndex: 0 },
{ id: 'v118', family: 'vocab', tier: 1, form: 'vocab', prompt: 'milk = ?', choices: ['นม', 'น้ำ', 'น้ำผึ้ง', 'โยเกิร์ต'], correctIndex: 0 },
{ id: 'v119', family: 'vocab', tier: 1, form: 'vocab', prompt: 'water = ?', choices: ['น้ำ', 'นม', 'น้ำอัดลม', 'น้ำแข็ง'], correctIndex: 0 },
{ id: 'v120', family: 'vocab', tier: 1, form: 'vocab', prompt: 'apple = ?', choices: ['แอปเปิล', 'ส้ม', 'องุ่น', 'มะม่วง'], correctIndex: 0 },
{ id: 'v121', family: 'vocab', tier: 1, form: 'vocab', prompt: 'banana = ?', choices: ['กล้วย', 'แอปเปิล', 'มะละกอ', 'สับปะรด'], correctIndex: 0 },
{ id: 'v122', family: 'vocab', tier: 1, form: 'vocab', prompt: 'book = ?', choices: ['หนังสือ', 'สมุด', 'ดินสอ', 'ปากกา'], correctIndex: 0 },
{ id: 'v123', family: 'vocab', tier: 1, form: 'vocab', prompt: 'pencil = ?', choices: ['ดินสอ', 'ปากกา', 'ยางลบ', 'สี'], correctIndex: 0 },
{ id: 'v124', family: 'vocab', tier: 1, form: 'vocab', prompt: 'teacher = ?', choices: ['ครู', 'นักเรียน', 'ผู้อำนวยการ', 'พ่อ'], correctIndex: 0 },
{ id: 'v125', family: 'vocab', tier: 1, form: 'vocab', prompt: 'student = ?', choices: ['นักเรียน', 'ครู', 'เพื่อน', 'เด็ก'], correctIndex: 0 },
{ id: 'v126', family: 'vocab', tier: 1, form: 'vocab', prompt: 'school = ?', choices: ['โรงเรียน', 'บ้าน', 'วัด', 'ตลาด'], correctIndex: 0 },
{ id: 'v127', family: 'vocab', tier: 1, form: 'vocab', prompt: 'hand = ?', choices: ['มือ', 'เท้า', 'แขน', 'นิ้ว'], correctIndex: 0 },
{ id: 'v128', family: 'vocab', tier: 1, form: 'vocab', prompt: 'eye = ?', choices: ['ตา', 'หู', 'คิ้ว', 'ปาก'], correctIndex: 0 },
{ id: 'v129', family: 'vocab', tier: 1, form: 'vocab', prompt: 'nose = ?', choices: ['จมูก', 'ปาก', 'หู', 'คอ'], correctIndex: 0 },
{ id: 'v130', family: 'vocab', tier: 1, form: 'vocab', prompt: 'ear = ?', choices: ['หู', 'ตา', 'จมูก', 'แก้ม'], correctIndex: 0 },

/* ---------- tier 2 · ป.4–6 · daily routine, time, weather, travel, places ---------- */
{ id: 'v201', family: 'vocab', tier: 2, form: 'vocab', prompt: 'breakfast = ?', choices: ['อาหารเช้า', 'อาหารกลางวัน', 'อาหารเย็น', 'ของว่าง'], correctIndex: 0 },
{ id: 'v202', family: 'vocab', tier: 2, form: 'vocab', prompt: 'dinner = ?', choices: ['อาหารเย็น', 'อาหารเช้า', 'อาหารกลางวัน', 'ของหวาน'], correctIndex: 0 },
{ id: 'v203', family: 'vocab', tier: 2, form: 'vocab', prompt: 'morning = ?', choices: ['ตอนเช้า', 'ตอนเย็น', 'ตอนบ่าย', 'ตอนกลางคืน'], correctIndex: 0 },
{ id: 'v204', family: 'vocab', tier: 2, form: 'vocab', prompt: 'night = ?', choices: ['กลางคืน', 'กลางวัน', 'ตอนเช้า', 'พลบค่ำ'], correctIndex: 0 },
{ id: 'v205', family: 'vocab', tier: 2, form: 'vocab', prompt: 'walk = ?', choices: ['เดิน', 'วิ่ง', 'กระโดด', 'นั่ง'], correctIndex: 0 },
{ id: 'v206', family: 'vocab', tier: 2, form: 'vocab', prompt: 'run = ?', choices: ['วิ่ง', 'เดิน', 'ยืน', 'เตะ'], correctIndex: 0 },
{ id: 'v207', family: 'vocab', tier: 2, form: 'vocab', prompt: 'sleep = ?', choices: ['นอนหลับ', 'ตื่น', 'ง่วง', 'พักผ่อน'], correctIndex: 0 },
{ id: 'v208', family: 'vocab', tier: 2, form: 'vocab', prompt: 'buy = ?', choices: ['ซื้อ', 'ขาย', 'แลก', 'ยืม'], correctIndex: 0 },
{ id: 'v209', family: 'vocab', tier: 2, form: 'vocab', prompt: 'sell = ?', choices: ['ขาย', 'ซื้อ', 'ส่ง', 'ฝาก'], correctIndex: 0 },
{ id: 'v210', family: 'vocab', tier: 2, form: 'vocab', prompt: 'help = ?', choices: ['ช่วย', 'ขัดขวาง', 'ถาม', 'ต่อว่า'], correctIndex: 0 },
{ id: 'v211', family: 'vocab', tier: 2, form: 'vocab', prompt: 'read = ?', choices: ['อ่าน', 'เขียน', 'ดู', 'ฟัง'], correctIndex: 0 },
{ id: 'v212', family: 'vocab', tier: 2, form: 'vocab', prompt: 'write = ?', choices: ['เขียน', 'อ่าน', 'วาด', 'พิมพ์'], correctIndex: 0 },
{ id: 'v213', family: 'vocab', tier: 2, form: 'vocab', prompt: 'listen = ?', choices: ['ฟัง', 'พูด', 'ดู', 'ร้อง'], correctIndex: 0 },
{ id: 'v214', family: 'vocab', tier: 2, form: 'vocab', prompt: 'speak = ?', choices: ['พูด', 'ฟัง', 'อ่าน', 'เงียบ'], correctIndex: 0 },
{ id: 'v215', family: 'vocab', tier: 2, form: 'vocab', prompt: 'watch = ?', choices: ['ดู', 'นาฬิกา', 'ซื้อ', 'ปิด'], correctIndex: 0 },
{ id: 'v216', family: 'vocab', tier: 2, form: 'vocab', prompt: 'rain = ?', choices: ['ฝน', 'หิมะ', 'ลม', 'แดด'], correctIndex: 0 },
{ id: 'v217', family: 'vocab', tier: 2, form: 'vocab', prompt: 'hot = ?', choices: ['ร้อน', 'หนาว', 'อุ่น', 'เย็น'], correctIndex: 0 },
{ id: 'v218', family: 'vocab', tier: 2, form: 'vocab', prompt: 'cold = ?', choices: ['หนาว', 'ร้อน', 'อุ่น', 'เย็น'], correctIndex: 0 },
{ id: 'v219', family: 'vocab', tier: 2, form: 'vocab', prompt: 'bus = ?', choices: ['รถเมล์', 'รถไฟ', 'รถยนต์', 'เครื่องบิน'], correctIndex: 0 },
{ id: 'v220', family: 'vocab', tier: 2, form: 'vocab', prompt: 'train = ?', choices: ['รถไฟ', 'รถเมล์', 'เรือ', 'จักรยาน'], correctIndex: 0 },
{ id: 'v221', family: 'vocab', tier: 2, form: 'vocab', prompt: 'airport = ?', choices: ['สนามบิน', 'สถานีรถไฟ', 'ท่าเรือ', 'ป้ายรถเมล์'], correctIndex: 0 },
{ id: 'v222', family: 'vocab', tier: 2, form: 'vocab', prompt: 'market = ?', choices: ['ตลาด', 'ห้าง', 'ร้านค้า', 'โรงหนัง'], correctIndex: 0 },
{ id: 'v223', family: 'vocab', tier: 2, form: 'vocab', prompt: 'hospital = ?', choices: ['โรงพยาบาล', 'โรงเรียน', 'โรงแรม', 'โรงงาน'], correctIndex: 0 },
{ id: 'v224', family: 'vocab', tier: 2, form: 'vocab', prompt: 'shirt = ?', choices: ['เสื้อ', 'กางเกง', 'รองเท้า', 'หมวก'], correctIndex: 0 },
{ id: 'v225', family: 'vocab', tier: 2, form: 'vocab', prompt: 'shoes = ?', choices: ['รองเท้า', 'ถุงเท้า', 'รองเท้าแตะ', 'สนับแข้ง'], correctIndex: 0 },
{ id: 'v226', family: 'vocab', tier: 2, form: 'vocab', prompt: 'bag = ?', choices: ['กระเป๋า', 'กระเป๋าเป้', 'รถเข็น', 'กล่อง'], correctIndex: 0 },
{ id: 'v227', family: 'vocab', tier: 2, form: 'vocab', prompt: 'umbrella = ?', choices: ['ร่ม', 'แว่นกันแดด', 'หมวก', 'ผ้าเช็ดตัว'], correctIndex: 0 },
{ id: 'v228', family: 'vocab', tier: 2, form: 'vocab', prompt: 'weekend = ?', choices: ['สุดสัปดาห์', 'วันธรรมดา', 'วันหยุดปีใหม่', 'วันเกิด'], correctIndex: 0 },
{ id: 'v229', family: 'vocab', tier: 2, form: 'vocab', prompt: 'holiday = ?', choices: ['วันหยุด', 'วันทำงาน', 'วันสอบ', 'วันจ่ายเงิน'], correctIndex: 0 },
{ id: 'v230', family: 'vocab', tier: 2, form: 'vocab', prompt: 'food = ?', choices: ['อาหาร', 'เครื่องดื่ม', 'ของใช้', 'ยา'], correctIndex: 0 },

/* ---------- tier 3 · ม.ต้น · everyday life, travel, feelings, society ---------- */
{ id: 'v301', family: 'vocab', tier: 3, form: 'vocab', prompt: 'travel = ?', choices: ['เดินทาง', 'พักผ่อน', 'ทำงาน', 'กลับบ้าน'], correctIndex: 0 },
{ id: 'v302', family: 'vocab', tier: 3, form: 'vocab', prompt: 'important = ?', choices: ['สำคัญ', 'ธรรมดา', 'ง่าย', 'ยาก'], correctIndex: 0 },
{ id: 'v303', family: 'vocab', tier: 3, form: 'vocab', prompt: 'dangerous = ?', choices: ['อันตราย', 'ปลอดภัย', 'สนุก', 'น่าเบื่อ'], correctIndex: 0 },
{ id: 'v304', family: 'vocab', tier: 3, form: 'vocab', prompt: 'safe = ?', choices: ['ปลอดภัย', 'อันตราย', 'เร็ว', 'ช้า'], correctIndex: 0 },
{ id: 'v305', family: 'vocab', tier: 3, form: 'vocab', prompt: 'busy = ?', choices: ['ยุ่ง', 'ว่าง', 'เหนื่อย', 'ง่วง'], correctIndex: 0 },
{ id: 'v306', family: 'vocab', tier: 3, form: 'vocab', prompt: 'excited = ?', choices: ['ตื่นเต้น', 'ตกใจ', 'เฉยๆ', 'กลัว'], correctIndex: 0 },
{ id: 'v307', family: 'vocab', tier: 3, form: 'vocab', prompt: 'tired = ?', choices: ['เหนื่อย', 'เบื่อ', 'หิว', 'โกรธ'], correctIndex: 0 },
{ id: 'v308', family: 'vocab', tier: 3, form: 'vocab', prompt: 'healthy = ?', choices: ['สุขภาพดี', 'ป่วย', 'อ่อนแอ', 'แข็งแรงพิเศษ'], correctIndex: 0 },
{ id: 'v309', family: 'vocab', tier: 3, form: 'vocab', prompt: 'cheap = ?', choices: ['ถูก', 'แพง', 'ฟรี', 'คุ้มค่า'], correctIndex: 0 },
{ id: 'v310', family: 'vocab', tier: 3, form: 'vocab', prompt: 'expensive = ?', choices: ['แพง', 'ถูก', 'หรูหรา', 'ล้ำสมัย'], correctIndex: 0 },
{ id: 'v311', family: 'vocab', tier: 3, form: 'vocab', prompt: 'delicious = ?', choices: ['อร่อย', 'จืด', 'หวาน', 'เผ็ด'], correctIndex: 0 },
{ id: 'v312', family: 'vocab', tier: 3, form: 'vocab', prompt: 'decide = ?', choices: ['ตัดสินใจ', 'เปลี่ยนใจ', 'ลังเล', 'ยอมแพ้'], correctIndex: 0 },
{ id: 'v313', family: 'vocab', tier: 3, form: 'vocab', prompt: 'agree = ?', choices: ['เห็นด้วย', 'ไม่เห็นด้วย', 'ถาม', 'แนะนำ'], correctIndex: 0 },
{ id: 'v314', family: 'vocab', tier: 3, form: 'vocab', prompt: 'return = ?', choices: ['ส่งคืน', 'ยืม', 'ขาย', 'ทิ้ง'], correctIndex: 0 },
{ id: 'v315', family: 'vocab', tier: 3, form: 'vocab', prompt: 'promise = ?', choices: ['สัญญา', 'ขอโทษ', 'ขอบคุณ', 'ชม'], correctIndex: 0 },
{ id: 'v316', family: 'vocab', tier: 3, form: 'vocab', prompt: 'invite = ?', choices: ['เชิญ', 'ไล่', 'ตาม', 'รอ'], correctIndex: 0 },
{ id: 'v317', family: 'vocab', tier: 3, form: 'vocab', prompt: 'visit = ?', choices: ['ไปเยี่ยม', 'ย้ายออก', 'โทรหา', 'ส่งของ'], correctIndex: 0 },
{ id: 'v318', family: 'vocab', tier: 3, form: 'vocab', prompt: 'arrive = ?', choices: ['มาถึง', 'ออกเดินทาง', 'กลับ', 'ผ่าน'], correctIndex: 0 },
{ id: 'v319', family: 'vocab', tier: 3, form: 'vocab', prompt: 'depart = ?', choices: ['ออกเดินทาง', 'มาถึง', 'จอดพัก', 'เปลี่ยนเที่ยว'], correctIndex: 0 },
{ id: 'v320', family: 'vocab', tier: 3, form: 'vocab', prompt: 'flight = ?', choices: ['เที่ยวบิน', 'สนามบิน', 'ตั๋ว', 'เครื่องบิน'], correctIndex: 0 },
{ id: 'v321', family: 'vocab', tier: 3, form: 'vocab', prompt: 'passenger = ?', choices: ['ผู้โดยสาร', 'นักบิน', 'คนขับ', 'พนักงานต้อนรับ'], correctIndex: 0 },
{ id: 'v322', family: 'vocab', tier: 3, form: 'vocab', prompt: 'ticket = ?', choices: ['ตั๋ว', 'บัตรประชาชน', 'เหรียญ', 'ที่นั่ง'], correctIndex: 0 },
{ id: 'v323', family: 'vocab', tier: 3, form: 'vocab', prompt: 'luggage = ?', choices: ['กระเป๋าเดินทาง', 'ตั๋ว', 'เสื้อผ้า', 'ของฝาก'], correctIndex: 0 },
{ id: 'v324', family: 'vocab', tier: 3, form: 'vocab', prompt: 'news = ?', choices: ['ข่าว', 'หนังสือพิมพ์', 'ข้อมูล', 'นิทาน'], correctIndex: 0 },
{ id: 'v325', family: 'vocab', tier: 3, form: 'vocab', prompt: 'weather = ?', choices: ['สภาพอากาศ', 'ฤดูกาล', 'อุณหภูมิ', 'พยากรณ์'], correctIndex: 0 },
{ id: 'v326', family: 'vocab', tier: 3, form: 'vocab', prompt: 'temperature = ?', choices: ['อุณหภูมิ', 'ความชื้น', 'ลม', 'ฝน'], correctIndex: 0 },
{ id: 'v327', family: 'vocab', tier: 3, form: 'vocab', prompt: 'traffic = ?', choices: ['การจราจร', 'ถนน', 'รถยนต์', 'ทางด่วน'], correctIndex: 0 },
{ id: 'v328', family: 'vocab', tier: 3, form: 'vocab', prompt: 'pollution = ?', choices: ['มลพิษ', 'ควันพิษ', 'ขยะ', 'สิ่งแวดล้อม'], correctIndex: 0 },
{ id: 'v329', family: 'vocab', tier: 3, form: 'vocab', prompt: 'energy = ?', choices: ['พลังงาน', 'แรง', 'ไฟฟ้า', 'น้ำมัน'], correctIndex: 0 },
{ id: 'v330', family: 'vocab', tier: 3, form: 'vocab', prompt: 'future = ?', choices: ['อนาคต', 'อดีต', 'ปัจจุบัน', 'ความฝัน'], correctIndex: 0 },

/* ---------- tier 4 · ม.ปลาย+ · business / news / society (en→th 18 + synonym 12) ---------- */
{ id: 'v401', family: 'vocab', tier: 4, form: 'vocab', prompt: 'company = ?', choices: ['บริษัท', 'โรงงาน', 'ร้านค้า', 'ห้างสรรพสินค้า'], correctIndex: 0 },
{ id: 'v402', family: 'vocab', tier: 4, form: 'vocab', prompt: 'manager = ?', choices: ['ผู้จัดการ', 'พนักงาน', 'เจ้าของบริษัท', 'ลูกค้า'], correctIndex: 0 },
{ id: 'v403', family: 'vocab', tier: 4, form: 'vocab', prompt: 'salary = ?', choices: ['เงินเดือน', 'ค่าจ้างรายชั่วโมง', 'โบนัส', 'ภาษี'], correctIndex: 0 },
{ id: 'v404', family: 'vocab', tier: 4, form: 'vocab', prompt: 'customer = ?', choices: ['ลูกค้า', 'ผู้จัดการ', 'พนักงาน', 'ผู้ขาย'], correctIndex: 0 },
{ id: 'v405', family: 'vocab', tier: 4, form: 'vocab', prompt: 'employee = ?', choices: ['พนักงาน', 'นายจ้าง', 'ผู้จัดการ', 'ลูกค้า'], correctIndex: 0 },
{ id: 'v406', family: 'vocab', tier: 4, form: 'vocab', prompt: 'meeting = ?', choices: ['การประชุม', 'การนัดหมาย', 'สัมมนา', 'การสัมภาษณ์'], correctIndex: 0 },
{ id: 'v407', family: 'vocab', tier: 4, form: 'vocab', prompt: 'report = ?', choices: ['รายงาน', 'ข้อเสนอ', 'เอกสาร', 'บันทึก'], correctIndex: 0 },
{ id: 'v408', family: 'vocab', tier: 4, form: 'vocab', prompt: 'deadline = ?', choices: ['กำหนดส่ง', 'วันนัด', 'ตารางเวลา', 'คิว'], correctIndex: 0 },
{ id: 'v409', family: 'vocab', tier: 4, form: 'vocab', prompt: 'contract = ?', choices: ['สัญญา', 'ข้อตกลงใจ', 'เอกสารสิทธิ', 'ใบเสร็จ'], correctIndex: 0 },
{ id: 'v410', family: 'vocab', tier: 4, form: 'vocab', prompt: 'profit = ?', choices: ['กำไร', 'รายได้', 'ขาดทุน', 'ค่าใช้จ่าย'], correctIndex: 0 },
{ id: 'v411', family: 'vocab', tier: 4, form: 'vocab', prompt: 'loss = ?', choices: ['ขาดทุน', 'กำไร', 'หนี้', 'ภาระ'], correctIndex: 0 },
{ id: 'v412', family: 'vocab', tier: 4, form: 'vocab', prompt: 'invest = ?', choices: ['ลงทุน', 'ออมเงิน', 'กู้เงิน', 'ขายออก'], correctIndex: 0 },
{ id: 'v413', family: 'vocab', tier: 4, form: 'vocab', prompt: 'economy = ?', choices: ['เศรษฐกิจ', 'การเมือง', 'สังคม', 'ตลาดหุ้น'], correctIndex: 0 },
{ id: 'v414', family: 'vocab', tier: 4, form: 'vocab', prompt: 'government = ?', choices: ['รัฐบาล', 'ประชาชน', 'บริษัท', 'สภาผู้แทน'], correctIndex: 0 },
{ id: 'v415', family: 'vocab', tier: 4, form: 'vocab', prompt: 'election = ?', choices: ['การเลือกตั้ง', 'การเมือง', 'การปกครอง',  'การลงมติ'], correctIndex: 0 },
{ id: 'v416', family: 'vocab', tier: 4, form: 'vocab', prompt: 'society = ?', choices: ['สังคม', 'ชุมชน', 'ประเทศ', 'ครอบครัว'], correctIndex: 0 },
{ id: 'v417', family: 'vocab', tier: 4, form: 'vocab', prompt: 'education = ?', choices: ['การศึกษา', 'โรงเรียน', 'ความรู้', 'การสอน'], correctIndex: 0 },
{ id: 'v418', family: 'vocab', tier: 4, form: 'vocab', prompt: 'technology = ?', choices: ['เทคโนโลยี', 'วิทยาศาสตร์', 'นวัตกรรม', 'อินเทอร์เน็ต'], correctIndex: 0 },

/* ---------- tier 4 · synonym (en≈en) ---------- */
{ id: 'v419', family: 'vocab', tier: 4, form: 'syn', prompt: 'fast ≈ ?', choices: ['quick', 'slow', 'late', 'strong'], correctIndex: 0 },
{ id: 'v420', family: 'vocab', tier: 4, form: 'syn', prompt: 'happy ≈ ?', choices: ['glad', 'sad', 'angry', 'tired'], correctIndex: 0 },
{ id: 'v421', family: 'vocab', tier: 4, form: 'syn', prompt: 'big ≈ ?', choices: ['large', 'small', 'short', 'tiny'], correctIndex: 0 },
{ id: 'v422', family: 'vocab', tier: 4, form: 'syn', prompt: 'smart ≈ ?', choices: ['clever', 'silly', 'lazy', 'kind'], correctIndex: 0 },
{ id: 'v423', family: 'vocab', tier: 4, form: 'syn', prompt: 'begin ≈ ?', choices: ['start', 'finish', 'end', 'stop'], correctIndex: 0 },
{ id: 'v424', family: 'vocab', tier: 4, form: 'syn', prompt: 'exhausted ≈ ?', choices: ['very tired', 'very bored', 'very sleepy', 'very relaxed'], correctIndex: 0 },
{ id: 'v425', family: 'vocab', tier: 4, form: 'syn', prompt: 'rich ≈ ?', choices: ['wealthy', 'poor', 'famous', 'greedy'], correctIndex: 0 },
{ id: 'v426', family: 'vocab', tier: 4, form: 'syn', prompt: 'brave ≈ ?', choices: ['courageous', 'shy', 'weak', 'rude'], correctIndex: 0 },
{ id: 'v427', family: 'vocab', tier: 4, form: 'syn', prompt: 'strange ≈ ?', choices: ['weird', 'normal', 'common', 'dull'], correctIndex: 0 },
{ id: 'v428', family: 'vocab', tier: 4, form: 'syn', prompt: 'furious ≈ ?', choices: ['very angry', 'very calm', 'very quiet', 'very polite'], correctIndex: 0 },
{ id: 'v429', family: 'vocab', tier: 4, form: 'syn', prompt: 'quiet ≈ ?', choices: ['silent', 'noisy', 'loud', 'busy'], correctIndex: 0 },
{ id: 'v430', family: 'vocab', tier: 4, form: 'syn', prompt: 'difficult ≈ ?', choices: ['hard', 'easy', 'simple', 'soft'], correctIndex: 0 },
];

global.EXPRESS_BANK_VOCAB = ITEMS;
if (typeof module !== 'undefined' && module.exports) module.exports = { VOCAB: ITEMS };
})(typeof window !== 'undefined' ? window : globalThis);
