// bank-context.js — PURE DATA: context bank (60 items) transcribed from docs/story.md.
// Item = { id, family:'context', tier:3|4, form:'context', passage, stem, choices[4], correctIndex }
// Convention: correct answer FIRST (correctIndex 0) — sampler shuffles position at serve time.
// passage: 2–3 sentences, ≤40 words, English. stem: Thai question.
// Distractor taxonomy (docs/story.md): true-but-not-asked · inverted/opposite · too broad/too narrow.
// Question mix per tier: ~60% main idea, ~25% detail, ~15% vocab-in-context.
(function (global) {
'use strict';

const ITEMS = [
/* ---------- tier 3 · ม.ต้น · school, daily life, travel, weekend ---------- */
{ id: 'c301', family: 'context', tier: 3, form: 'context',
  passage: 'Nok loves science class. Every Friday, she does experiments with her friends in the lab. She wants to be a doctor one day.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Nok enjoys science and has a dream job', 'Nok is good at English', 'The class does experiments every day', "Nok's friend wants to be a doctor"], correctIndex: 0 },
{ id: 'c302', family: 'context', tier: 3, form: 'context',
  passage: 'Dad wakes up at five every morning. He cooks breakfast for the family before he goes to work at the bank.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Dad has an early morning routine', 'Dad works as a teacher', 'The family cooks together', 'Dad goes to bed at five'], correctIndex: 0 },
{ id: 'c303', family: 'context', tier: 3, form: 'context',
  passage: 'Tomorrow is Sports Day at school. Pim will run in the relay race. She practices with her team after class every day.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Pim is preparing for a race', 'Pim does not like sports', 'Sports Day was yesterday', 'The team won the race'], correctIndex: 0 },
{ id: 'c304', family: 'context', tier: 3, form: 'context',
  passage: 'The blue bus goes to the market every fifteen minutes. It costs ten baht. Many students take it to school in the morning.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The passage describes a bus route and its price', 'The bus goes to the airport', 'The bus costs fifty baht', 'Students drive cars to school'], correctIndex: 0 },
{ id: 'c305', family: 'context', tier: 3, form: 'context',
  passage: 'Keng forgot his umbrella. On the way home, it started to rain. He ran fast, but his shirt was wet when he arrived.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Keng got caught in the rain', 'Keng loves rainy days', 'The rain stopped before he left', 'Keng left his shirt at school'], correctIndex: 0 },
{ id: 'c306', family: 'context', tier: 3, form: 'context',
  passage: "Grandma's noodles are famous on our street. She opens her shop at six in the morning. By noon, everything is sold out.",
  stem: 'ร้านของยายขายหมดเมื่อไหร่?',
  choices: ['By noon', 'At six in the morning', 'In the evening', 'On the weekend'], correctIndex: 0 },
{ id: 'c307', family: 'context', tier: 3, form: 'context',
  passage: 'Mali went to Chiang Mai last month. She visited Doi Suthep and ate khao soi. She says the weather was cool at night.',
  stem: 'อาหารที่ Mali กินคืออะไร?',
  choices: ['Khao soi', 'Doi Suthep', 'Cool weather', 'Som tam'], correctIndex: 0 },
{ id: 'c308', family: 'context', tier: 3, form: 'context',
  passage: 'The library is quiet on weekdays. Only five students were there on Tuesday. During exam week, it is full and noisy.',
  stem: 'ห้องสมุดคับคั่งเมื่อไหร่?',
  choices: ['During exam week', 'On weekdays', 'On Tuesday', 'Every morning'], correctIndex: 0 },
{ id: 'c309', family: 'context', tier: 3, form: 'context',
  passage: 'Tan sells fresh orange juice at the park. He uses eight oranges for one bottle. His juice is sweet because he adds no sugar.',
  stem: "'fresh' ใน passage หมายถึงอะไร?",
  choices: ['Newly made, not old', 'Frozen', 'Expensive', 'Sour'], correctIndex: 0 },
{ id: 'c310', family: 'context', tier: 3, form: 'context',
  passage: "Ploy's birthday is on Saturday. She invited ten friends to her house. Her mother will bake a chocolate cake for the party.",
  stem: 'ใครทำเค้ก?',
  choices: ["Ploy's mother", 'Ploy', 'Ten friends', 'A baker'], correctIndex: 0 },
{ id: 'c311', family: 'context', tier: 3, form: 'context',
  passage: 'Our school football team lost the game last Friday. The score was two to one. The players practiced harder the next week.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The team lost, so they practiced harder', 'The team won the game', 'The score was three to one', 'The players quit the team'], correctIndex: 0 },
{ id: 'c312', family: 'context', tier: 3, form: 'context',
  passage: 'The train to Ayutthaya leaves at 8:15. The journey takes about one hour and twenty minutes. Tickets are cheaper on weekdays.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The passage gives facts about a train trip', 'The train is faster than the bus', 'Tickets are cheaper on weekends', 'The journey takes twenty minutes'], correctIndex: 0 },
{ id: 'c313', family: 'context', tier: 3, form: 'context',
  passage: 'Nita saved money for three months. She bought a bicycle for her little brother. He rides it to school every day now.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Nita used her savings to buy her brother a bicycle', 'Nita sold her bicycle', 'Her brother saved the money', 'The bicycle was a gift from school'], correctIndex: 0 },
{ id: 'c314', family: 'context', tier: 3, form: 'context',
  passage: 'The rain season in Thailand starts around May. Farmers plant rice when the first heavy rains come. The fields turn green quickly.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The rains mark the start of rice farming', 'Farmers hate the rain', 'Rice grows only in winter', 'The fields turn brown'], correctIndex: 0 },
{ id: 'c315', family: 'context', tier: 3, form: 'context',
  passage: 'At the night market, you can try many kinds of food. The mango sticky rice stall has the longest line every weekend.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['One food stall is very popular at the market', 'The market sells only fruit', 'Nobody buys mango sticky rice', 'The market opens in the morning'], correctIndex: 0 },
{ id: 'c316', family: 'context', tier: 3, form: 'context',
  passage: "Ken's phone battery died during the trip. He could not check the map. Luckily, a kind old man showed him the way to the station.",
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['A stranger helped Ken find the station', "Ken's phone worked well", 'The old man was lost', 'Ken took a taxi'], correctIndex: 0 },
{ id: 'c317', family: 'context', tier: 3, form: 'context',
  passage: 'Fah does her homework right after school. Then she helps wash the dishes. After dinner, she watches cartoons for thirty minutes.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The passage describes what Fah does after school', 'Fah never helps at home', 'Fah does homework after dinner', 'Fah watches TV all evening'], correctIndex: 0 },
{ id: 'c318', family: 'context', tier: 3, form: 'context',
  passage: 'The science museum is free on Sundays. Many families wait in line before it opens at nine. The dinosaur room is the most popular.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The museum is busy on free days', 'The museum is always empty', 'Tickets cost a lot', 'The art room is most popular'], correctIndex: 0 },
{ id: 'c319', family: 'context', tier: 3, form: 'context',
  passage: 'Jeab missed the school bus. Her neighbor drove her to school on his motorbike. She arrived just before the bell rang.',
  stem: 'Jeab ไปโรงเรียนด้วยอะไร?',
  choices: ["Her neighbor's motorbike", 'The school bus', 'She walked', 'A taxi'], correctIndex: 0 },
{ id: 'c320', family: 'context', tier: 3, form: 'context',
  passage: 'Petch waters the plants every evening. The roses grow well, but the orchids need more shade. He moves them under the tree.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Petch gives different care to different plants', 'All the plants need more water', 'The roses die', 'Petch sells orchids'], correctIndex: 0 },
{ id: 'c321', family: 'context', tier: 3, form: 'context',
  passage: 'Aree takes the boat to work every day. The ride takes twenty minutes. She likes it better than the traffic on the roads.',
  stem: "'traffic' ใน passage หมายถึงอะไร?",
  choices: ['Cars moving on the roads', 'Boats on the river', 'People walking', 'Heavy rain'], correctIndex: 0 },
{ id: 'c322', family: 'context', tier: 3, form: 'context',
  passage: 'The camping trip was almost canceled because of the storm. In the end, the sky cleared on Saturday morning. Eleven students joined.',
  stem: 'ทริปตั้งแคมป์เกิดขึ้นได้เพราะอะไร?',
  choices: ['The sky cleared', 'The storm continued', 'Eleven students paid', 'The trip was canceled'], correctIndex: 0 },
{ id: 'c323', family: 'context', tier: 3, form: 'context',
  passage: 'Nut practices the guitar for one hour after dinner. His little sister sings along. On Sundays, they perform for their grandparents.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Nut and his sister make music together', 'Nut plays the piano', 'His sister hates singing', 'They perform at school'], correctIndex: 0 },
{ id: 'c324', family: 'context', tier: 3, form: 'context',
  passage: 'The bakery smells wonderful at six a.m. Fresh bread comes out of the oven every hour. The croissants sell out before nine.',
  stem: "'sell out' หมายถึงอะไร?",
  choices: ['Are all bought', 'Are thrown away', 'Become cheaper', 'Are baked'], correctIndex: 0 },
{ id: 'c325', family: 'context', tier: 3, form: 'context',
  passage: 'Kanda wants a part-time job at the bookstore. She can work on weekends. The store needs someone who loves books and can use a computer.',
  stem: 'ร้านหนังสือต้องการคนแบบไหน?',
  choices: ['Someone who loves books and can use a computer', 'Someone who works weekdays only', 'Someone with a car', 'A full-time manager'], correctIndex: 0 },
{ id: 'c326', family: 'context', tier: 3, form: 'context',
  passage: 'During Songkran, the streets are full of water fights. People also visit their elders and pour scented water on their hands.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Songkran has playful and respectful traditions', 'Songkran is only about water fights', 'Nobody works during Songkran', 'People pour coffee on hands'], correctIndex: 0 },
{ id: 'c327', family: 'context', tier: 3, form: 'context',
  passage: 'Ice rides his bicycle to the swimming pool. He swims twenty laps every visit. His coach says he may join the city team next year.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Ice trains seriously and may join a team', 'Ice is afraid of water', 'His coach swims twenty laps', 'Ice drives to the pool'], correctIndex: 0 },
{ id: 'c328', family: 'context', tier: 3, form: 'context',
  passage: 'The phone screen was cracked. Uncle Prem fixed it in one hour. He only asked for a bowl of noodles as payment.',
  stem: 'ลุงเพรมเอาอะไรเป็นค่าจ้าง?',
  choices: ['A bowl of noodles', 'One hour', 'A new phone', 'Money'], correctIndex: 0 },
{ id: 'c329', family: 'context', tier: 3, form: 'context',
  passage: 'Every Saturday, the park has a fun run. Anyone can join for free. Runners get a bottle of water and a medal at the finish line.',
  stem: 'นักวิ่งได้อะไรตอนจบ?',
  choices: ['Water and a medal', 'Free shoes', 'Money', 'A t-shirt'], correctIndex: 0 },
{ id: 'c330', family: 'context', tier: 3, form: 'context',
  passage: "Ying's family moved to a new apartment. It is smaller, but closer to her school. Now she walks to class in ten minutes.",
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The new home is smaller but more convenient', 'The new apartment is bigger', 'Ying takes the bus', 'The school moved closer'], correctIndex: 0 },

/* ---------- tier 4 · ม.ปลาย+ · business, news, technology, environment, health, society ---------- */
{ id: 'c401', family: 'context', tier: 4, form: 'context',
  passage: 'The startup began in a small garage with three employees. Today, it exports software to over forty countries. Its success came from listening to customers.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The company grew from small beginnings into a global exporter', 'The startup failed after three years', 'It sells clothes worldwide', 'Customers stopped buying'], correctIndex: 0 },
{ id: 'c402', family: 'context', tier: 4, form: 'context',
  passage: 'Remote work has changed city life. Fewer people buy lunch downtown, so some restaurants closed. However, delivery apps are busier than ever.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Remote work has mixed effects on local business', 'Remote work has no effect', 'All restaurants closed', 'Delivery apps lost customers'], correctIndex: 0 },
{ id: 'c403', family: 'context', tier: 4, form: 'context',
  passage: 'The new railway will connect three provinces. Construction starts next month and finishes in 2029. Officials expect travel time to drop by half.',
  stem: 'รถไฟเสร็จเมื่อไหร่?',
  choices: ['In 2029', 'Next month', 'In three provinces', 'In half a year'], correctIndex: 0 },
{ id: 'c404', family: 'context', tier: 4, form: 'context',
  passage: 'Scientists studied 1,000 office workers. Those who walked 30 minutes a day reported less stress. The study will continue for two more years.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Daily walking is linked to lower stress', 'Walking causes stress', 'Only 1,000 scientists walked', 'The study is finished'], correctIndex: 0 },
{ id: 'c405', family: 'context', tier: 4, form: 'context',
  passage: 'Electric car sales doubled this year. Prices fell because batteries became cheaper. Experts predict petrol stations will add charging points soon.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Cheaper batteries helped electric car sales grow', 'Petrol car sales doubled', 'Batteries became expensive', 'Experts banned petrol stations'], correctIndex: 0 },
{ id: 'c406', family: 'context', tier: 4, form: 'context',
  passage: "The company's quarterly report shows strong online sales. Store sales dropped slightly. The CEO plans to invest more in its app and website.",
  stem: 'ยอดขายหน้าร้านเป็นอย่างไร?',
  choices: ['Dropped slightly', 'Strong online', 'Doubled', 'Stayed the same'], correctIndex: 0 },
{ id: 'c407', family: 'context', tier: 4, form: 'context',
  passage: 'Plastic waste in the ocean harms sea animals. Turtles often mistake bags for jellyfish. A new law will ban thin plastic bags next year.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Plastic waste endangers sea life, so a ban is coming', 'Turtles eat only jellyfish', 'The law bans turtles', 'Plastic helps sea animals'], correctIndex: 0 },
{ id: 'c408', family: 'context', tier: 4, form: 'context',
  passage: 'Air quality in the city reached unsafe levels this week. Schools kept students indoors. Health officials advised people to wear masks outdoors.',
  stem: 'โรงเรียนทำอะไร?',
  choices: ['Kept students indoors', 'Cancelled all classes', 'Gave masks to students', 'Held classes outside'], correctIndex: 0 },
{ id: 'c409', family: 'context', tier: 4, form: 'context',
  passage: 'The app was designed to help farmers. It shows weather warnings and market prices. Over 50,000 farmers downloaded it in the first month.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['A new app gives farmers useful information', 'The app sells vegetables', 'Farmers designed the app', 'Only 500 farmers use it'], correctIndex: 0 },
{ id: 'c410', family: 'context', tier: 4, form: 'context',
  passage: 'Tourism is recovering slowly after the crisis. Hotels report 60% occupancy, up from 20% last year. Airlines have added new regional routes.',
  stem: "'occupancy' ใน passage หมายถึงอะไร?",
  choices: ['The share of rooms that are booked', 'The price of rooms', 'The number of hotel staff', 'The number of stars'], correctIndex: 0 },
{ id: 'c411', family: 'context', tier: 4, form: 'context',
  passage: 'Many offices now use flexible hours. Employees can start between seven and ten. Studies suggest productivity stays the same, but happiness rises.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Flexible hours keep productivity but improve well-being', 'Flexible hours cut productivity', 'All workers must start at seven', 'Happiness stays the same'], correctIndex: 0 },
{ id: 'c412', family: 'context', tier: 4, form: 'context',
  passage: 'The city will test free bus rides for six months. If passenger numbers rise, the program may become permanent. The goal is to reduce traffic congestion.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The city is testing free buses to cut traffic', 'Buses will be free forever', 'The program already ended', 'The goal is to sell more cars'], correctIndex: 0 },
{ id: 'c413', family: 'context', tier: 4, form: 'context',
  passage: 'A local bakery replaced plastic bags with paper ones. Costs rose slightly, but customers supported the change. Other shops on the street followed.',
  stem: 'ร้านเบเกอรี่ทำอะไร?',
  choices: ['Replaced plastic with paper bags', 'Raised prices a lot', 'Lost customers', 'Closed the shop'], correctIndex: 0 },
{ id: 'c414', family: 'context', tier: 4, form: 'context',
  passage: 'Online scams have tripled this year. Most victims shared their passwords by mistake. The bank now sends warnings before large transfers.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Scams are rising, often through shared passwords', 'Scams decreased', 'The bank gives money to victims', 'Passwords are safe to share'], correctIndex: 0 },
{ id: 'c415', family: 'context', tier: 4, form: 'context',
  passage: 'The old market will become a public park. Vendors will move to a new building nearby. Construction begins after the New Year festival.',
  stem: 'แผงค้าย้ายไปไหน?',
  choices: ['A new building nearby', 'The public park', 'Another city', 'They stay where they are'], correctIndex: 0 },
{ id: 'c416', family: 'context', tier: 4, form: 'context',
  passage: 'Video calls have replaced many business trips. Companies save money on flights and hotels. Some workers, however, miss meeting clients in person.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Video calls cut costs but lose some human connection', 'Video calls cost more', 'Companies banned travel forever', 'All workers prefer calls'], correctIndex: 0 },
{ id: 'c417', family: 'context', tier: 4, form: 'context',
  passage: "The hospital's new app lets patients book appointments. Waiting times dropped from two hours to twenty minutes. Elderly patients can get help by phone.",
  stem: 'เวลารอลดเหลือเท่าไหร่?',
  choices: ['Twenty minutes', 'Two hours', 'Two days', 'Twenty hours'], correctIndex: 0 },
{ id: 'c418', family: 'context', tier: 4, form: 'context',
  passage: 'Solar panels now cover the school roof. The school saves 40% on electricity. Students learn about renewable energy in the new lab.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Solar power saves money and teaches students', 'The school pays more for power', 'Panels cover the playground', 'The lab uses coal'], correctIndex: 0 },
{ id: 'c419', family: 'context', tier: 4, form: 'context',
  passage: 'City planners will add bicycle lanes on two main roads. Drivers worry about narrower streets. Cyclists welcome the safety upgrade.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The bike lane plan draws different reactions', 'Everyone supports the lanes', 'Cyclists worry about safety', 'The lanes are for buses'], correctIndex: 0 },
{ id: 'c420', family: 'context', tier: 4, form: 'context',
  passage: 'The unemployment rate fell to 2.1% this quarter. Tourism and technology jobs led the growth. Economists warn that wages have not risen yet.',
  stem: "'unemployment rate' หมายถึงอะไร?",
  choices: ['The share of people without jobs', 'The average pay', 'The prices of goods', 'The number of companies'], correctIndex: 0 },
{ id: 'c421', family: 'context', tier: 4, form: 'context',
  passage: 'A teenager invented a low-cost water filter. It turns rainwater into drinking water. Villages in three provinces already use his design.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ["A student's invention provides safe drinking water", 'The filter is expensive', 'Factories use the filter', 'He sells filters in malls'], correctIndex: 0 },
{ id: 'c422', family: 'context', tier: 4, form: 'context',
  passage: 'The library now lends laptops along with books. Students borrow them for one week. Late returns are free for the first three days.',
  stem: 'ยืมแล็ปท็อปได้นานเท่าไหร่?',
  choices: ['One week', 'Three days', 'One month', 'One day'], correctIndex: 0 },
{ id: 'c423', family: 'context', tier: 4, form: 'context',
  passage: 'Fast fashion creates huge amounts of waste. Some brands now recycle old clothes into new fabric. Shoppers can return used items for a discount.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Some clothing brands recycle to reduce waste', 'Fast fashion helps the environment', 'Shoppers must pay more', 'All brands recycle'], correctIndex: 0 },
{ id: 'c424', family: 'context', tier: 4, form: 'context',
  passage: 'The train station will add elevators for wheelchairs. Work starts in March. During construction, staff will help passengers on the old stairs.',
  stem: 'งานก่อสร้างเริ่มเมื่อไหร่?',
  choices: ['In March', 'With the elevators', 'After construction', 'In May'], correctIndex: 0 },
{ id: 'c425', family: 'context', tier: 4, form: 'context',
  passage: 'Working from cafes has become popular among freelancers. Coffee shops respond with faster Wi-Fi and more power outlets. Some set minimum spending on weekends.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Cafes change their services for remote workers', 'Freelancers dislike cafes', 'Wi-Fi became slower', 'Cafes ban laptops'], correctIndex: 0 },
{ id: 'c426', family: 'context', tier: 4, form: 'context',
  passage: 'The flood warning system now sends phone alerts. Residents get messages six hours before water arrives. Last year, the warning came only one hour early.',
  stem: 'ปีก่อนเตือนล่วงหน้ากี่ชั่วโมง?',
  choices: ['One hour', 'Six hours', 'Every year', 'Six minutes'], correctIndex: 0 },
{ id: 'c427', family: 'context', tier: 4, form: 'context',
  passage: 'Urban gardens are appearing on rooftops. Volunteers grow vegetables and share the harvest. The project also cools the buildings below.',
  stem: "'harvest' ใน passage หมายถึงอะไร?",
  choices: ['The crops that are gathered', 'The seeds', 'The soil', 'The rooftop'], correctIndex: 0 },
{ id: 'c428', family: 'context', tier: 4, form: 'context',
  passage: 'The company allows employees to bring pets one day a month. Surveys show morale improved. A few workers with allergies asked for quiet rooms.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['The pet day policy is popular with some exceptions', 'All workers love pets', 'Pets are banned', 'Allergies ended the policy'], correctIndex: 0 },
{ id: 'c429', family: 'context', tier: 4, form: 'context',
  passage: 'Digital payments overtook cash for the first time this year. Street vendors accept QR codes. Older customers still prefer coins and notes.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Digital payments now beat cash, but not for everyone', 'Cash disappeared completely', 'Vendors reject QR codes', 'Only the young pay digitally'], correctIndex: 0 },
{ id: 'c430', family: 'context', tier: 4, form: 'context',
  passage: 'Night shifts affect sleep, a new study finds. Workers who napped 20 minutes before shifts made fewer mistakes. Hospitals may add nap rooms.',
  stem: 'passage นี้กล่าวถึงอะไรเป็นหลัก?',
  choices: ['Short naps may reduce night-shift errors', 'Night shifts improve sleep', 'Naps cause mistakes', 'Hospitals banned naps'], correctIndex: 0 },
];

global.EXPRESS_BANK_CONTEXT = ITEMS;
if (typeof module !== 'undefined' && module.exports) module.exports = { CONTEXT: ITEMS };
})(typeof window !== 'undefined' ? window : globalThis);
